config/routes.rb
Rails.application.routes.draw do
  resources :expense_types

  resources :journals

  resources :accounts

  devise_for :users
  root to: "journals#index"

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to  :user

  validates_uniqueness_of :account_number
end

app/models/expense_type.rb
class ExpenseType < ActiveRecord::Base
  belongs_to :user
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
  belongs_to :account
  belongs_to :expense_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts
  has_many :journals
  has_many :expense_types
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout 'home'
#  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @accounts = Account.order('account_number')
    respond_with(@accounts)
  end

  def show
    respond_with(@account)
  end

  def new
    @account = current_user.accounts.new
    respond_with(@account)
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)
    @account.save
    redirect_to accounts_url
  end

  def update
    @account.update(account_params)
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:account_number, :account_name, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expense_types_controller.rb
class ExpenseTypesController < ApplicationController
  layout 'home'
  before_action :authenticate_user!
  before_action :set_expense_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @expense_types = ExpenseType.all
    respond_with(@expense_types)
  end

  def show
    respond_with(@expense_type)
  end

  def new
    @expense_type = ExpenseType.new
    respond_with(@expense_type)
  end

  def edit
  end

  def create
    @expense_type = ExpenseType.new(expense_type_params)
    @expense_type.save
    respond_with(@expense_type)
  end

  def update
    @expense_type.update(expense_type_params)
    respond_with(@expense_type)
  end

  def destroy
    @expense_type.destroy
    respond_with(@expense_type)
  end

  private
    def set_expense_type
      @expense_type = ExpenseType.find(params[:id])
    end

    def expense_type_params
      params.require(:expense_type).permit(:name, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  layout 'home'
  before_action :authenticate_user!
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @journals = current_user.journals.all
    respond_with(@journals)
  end

  def show
    respond_with(@journal)
  end

  def new
    @journal = current_user.journals.new
    respond_with(@journal)
  end

  def edit
  end

  def create
    @journal = current_user.journals.new(journal_params)
    @journal.save
    redirect_to journals_url
  end

  def update
    @journal.update(journal_params)
    respond_with(@journal)
  end

  def destroy
    @journal.destroy
    respond_with(@journal)
  end

  private
    def set_journal
      @journal = Journal.find(params[:id])
    end

    def journal_params
      params.require(:journal).permit(:journal_date, :payee, :description, :account_id, :amount, :user_id, :is_posted, :expense_type_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expense_types_helper.rb
module ExpenseTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @account.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h4>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :account_number, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :account_number, autofocus: true, class: "form-control floating-label", placeholder: "Account Number", size: 4 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :account_name, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :account_name, autocomplete: "off", :class => "form-control"%>
    </div>
  </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%= f.submit 'Save changes', :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @account, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing account</h1>
</div>

<%= render 'form' %>

app/views/accounts/index.html.erb
<div class="page-header">
  <button type="button" class="btn btn-fab btn-fab-mini btn-raised btn-sm btn-primary pull-right" data-toggle="modal" data-target="#myModal">
    <i class="mdi-content-add"></i>
  </button>
  <h3>Listing accounts</h3>
</div>

<div class="modal" id="myModal">
  <div class="modal-dialog" style="max-width: 80%">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Account</h4>
      </div>
      <div class="modal-body">
        <%  @account = current_user.accounts.new %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Account number</th>
            <th>Account name</th>
            <th>User</th>
            <th colspan="3">Action</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @accounts) do |account| %>
            <td><%= account.account_number %></td>
            <td><%= account.account_name %></td>
            <td><%= account.user.email %></td>
            <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-fab btn-raised btn-material-yellow-500' do %>
      <i class="mdi-navigation-arrow-back"></i>
  <% end %>
  <h1>New account</h1>
</div>

<%= render 'form' %>

app/views/accounts/show.html.erb
<div class="page-header">
  <%= link_to accounts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_account_path(@account), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show account</h1>
</div>

<dl class="dl-horizontal">
  <dt>Account number:</dt>
  <dd><%= @account.account_number %></dd>

  <dt>Account name:</dt>
  <dd><%= @account.account_name %></dd>

  <dt>User:</dt>
  <dd><%= @account.user_id %></dd>

</dl>

app/views/expense_types/_form.html.erb
<%= form_for(@expense_type, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @expense_type.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@expense_type.errors.count, "error") %> prohibited this expense_type from being saved:</h4>

      <ul>
      <% @expense_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, autofocus: true,:class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/expense_types/edit.html.erb
<div class="page-header">
  <%= link_to expense_types_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @expense_type, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing expense_type</h1>
</div>

<%= render 'form' %>

app/views/expense_types/index.html.erb
<div class="page-header">
  <button type="button" class="btn btn-fab btn-fab-mini btn-raised btn-sm btn-primary pull-right" data-toggle="modal" data-target="#myModal">
    <i class="mdi-content-add"></i>
  </button>
  <h3>Expense Types</h3>
</div>

<div class="modal" id="myModal">
  <div class="modal-dialog" style="max-width: 80%; margin-top: 12%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Journal Entry</h4>
      </div>
      <div class="modal-body">
        <%  @expense_type = current_user.expense_types.new %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @expense_types) do |expense_type| %>
            <td><%= expense_type.name %></td>
            <td><%= expense_type.user_id %></td>
            <td><%= link_to 'Show', expense_type %></td>
        <td><%= link_to 'Edit', edit_expense_type_path(expense_type) %></td>
        <td><%= link_to 'Destroy', expense_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/expense_types/new.html.erb
<div class="page-header">
  <%= link_to expense_types_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New expense_type</h1>
</div>

<%= render 'form' %>

app/views/expense_types/show.html.erb
<div class="page-header">
  <%= link_to expense_types_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_expense_type_path(@expense_type), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show expense_type</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @expense_type.name %></dd>

  <dt>User:</dt>
  <dd><%= @expense_type.user_id %></dd>

</dl>

app/views/home/index.erb
<div class="jumbotron">
  <h1>Jumbotron</h1>
  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>

app/views/journals/_form.html.erb
<%= form_for(@journal, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @journal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@journal.errors.count, "error") %> prohibited this journal from being saved:</h4>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :journal_date, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :journal_date, autofocus: true, value: Date.today, :class => "datepicker form-control floating-label", placeholder: "Date" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payee, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :payee, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :account_id, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.collection_select :account_id, Account.order(:account_number),:id,:account_name %>
    </div>
  </div>
    <div class="form-group">
      <%= f.label :expense_type_id, :class => "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.collection_select :expense_type_id, ExpenseType.order(:name),:id,:name %>
      </div>
    </div>
  <div class="form-group">
    <%= f.label :amount, :class => "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :amount, :class => "form-control", style: "text-align: right" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-danger pull-right" %>
    </div>
  </div>
<% end %>

<script>

</script>

app/views/journals/edit.html.erb
<div class="page-header">
  <%= link_to journals_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @journal, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing journal</h1>
</div>

<%= render 'form' %>

app/views/journals/index.html.erb
<div class="page-header">
  <button type="button" class="btn btn-fab btn-fab-mini btn-raised btn-sm btn-primary pull-right" data-toggle="modal" data-target="#myModal">
    <i class="mdi-content-add"></i>
  </button>
  <h3>Cash Journals</h3>
</div>

<div class="modal" id="myModal">
  <div class="modal-dialog" style="max-width: 80%; margin-top: 12%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">New Journal Entry</h4>
      </div>
      <div class="modal-body">
        <%  @journal = current_user.journals.new %>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>





<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Journal date</th>
            <th>Payee</th>
            <th>Description</th>
            <th>Account</th>
            <th>Expense Type</th>
            <th>Amount</th>
            <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @journals) do |journal| %>
            <td><%= journal.journal_date.strftime("%d/%m/%Y") %></td>
            <td><%= journal.payee %></td>
            <td><%= journal.description %></td>
            <td><%= journal.account.account_name %></td>
            <td><%= journal.expense_type.name unless journal.expense_type_id.blank? %></td>
            <td align="right"><%= number_to_currency(journal.amount, unit: "") %></td>
            <td><%= link_to 'Edit', edit_journal_path(journal) %></td>
            <td><%= link_to 'Delete', journal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/journals/new.html.erb
<div class="page-header">
  <%= link_to journals_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New journal</h1>
</div>

<%= render 'form' %>

app/views/journals/show.html.erb
<div class="page-header">
  <%= link_to journals_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_journal_path(@journal), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show journal</h1>
</div>

<dl class="dl-horizontal">
  <dt>Journal date:</dt>
  <dd><%= @journal.journal_date %></dd>

  <dt>Payee:</dt>
  <dd><%= @journal.payee %></dd>

  <dt>Description:</dt>
  <dd><%= @journal.description %></dd>

  <dt>Account:</dt>
  <dd><%= @journal.account_id %></dd>

  <dt>Amount:</dt>
  <dd><%= @journal.amount %></dd>

  <dt>User:</dt>
  <dd><%= @journal.user_id %></dd>

  <dt>Is posted:</dt>
  <dd><%= @journal.is_posted %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Servants of the Word Personal Finance</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    <div style="margin-top: 30px;">
    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Servants of the Word Personal Finance</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/ripples.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="javascript:void(0)">Servants of the Word</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to 'Cash Journal', root_url %></li>
      <li><%= link_to 'Accounts', accounts_url %></li>
      <li class="dropdown">
        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<%= expense_types_path %>">Expense Type</a></li>
          <li><a href="javascript:void(0)">Account Ledgers</a></li>
          <li><a href="javascript:void(0)">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="javascript:void(0)">Separated link</a></li>
          <li><a href="javascript:void(0)">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Hello, " + current_user.email + " [Click here to logout] ", destroy_user_session_path, :method => :delete%></li>
    </ul>
  </div>
</div>





<div class="container">
  <div style="margin-top: 30px;">
    <%= yield %>
  </div>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>
</div>
</body>
</html>